### PR TITLE
Update app_tr.arb

### PR DESCRIPTION
**Pull request by neoplus72**
3 lines fixed

### CODE REVIEW

**Comment by jithware** [comment]
@neoplus72 These are labels in the preferences indicating which audio sound to use when inhaling or exhaling.  According to [Google Translate](https://translate.google.com/?sl=en&tl=tr&text=Inhale%20Hold%20Audio%0AExhale%20Audio%0AExhale%20Hold%20Audio&op=translate) this update is not the correct translations. Do you natively speak Turkish? If so, is Google Translate incorrect?

**Comment by neoplus72** [comment]
> 



> @neoplus72 These are labels in the preferences indicating which audio sound to use when inhaling or exhaling. According to [Google Translate](https://translate.google.com/?sl=en&tl=tr&text=Inhale%20Hold%20Audio%0AExhale%20Audio%0AExhale%20Hold%20Audio&op=translate) this update is not the correct translations. Do you natively speak Turkish? If so, is Google Translate incorrect?

Yes my natural language is turkish .google translate cannot translate naturally

**Comment by neoplus72** [comment]
> @neoplus72 These are labels in the preferences indicating which audio sound to use when inhaling or exhaling. According to [Google Translate](https://translate.google.com/?sl=en&tl=tr&text=Inhale%20Hold%20Audio%0AExhale%20Audio%0AExhale%20Hold%20Audio&op=translate) this update is not the correct translations. Do you natively speak Turkish? If so, is Google Translate incorrect?

If you want a translation according to google translate, I can correct it, but it would be meaningless.

**Comment by jithware** [comment]
Because of the nuances of language, I strongly prefer native speakers to provide translations. Google Translate is not reliable and only used to verify a translation is "close". Since you are a native speaker, I prefer your translation. However "Derin bir nefes alıp tutun" translates to "Take a deep breath and hold" which has no indication of audio.

**Pull request closed without merging**
